# PostgreSQL. Versions 8.2 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: trello_development
  host: localhost

test:
  <<: *default
  database: trello_test

production:
  <<: *default
  database: trello_production
  username: trello
  password: <%= ENV['BOOKFRIENDS_DATABASE_PASSWORD'] %>
